# Generated by Django 6.0.1 on 2026-01-16 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contact_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['last_name', '-created']},
        ),
    ]
