# Generated by Django 6.0.1 on 2026-01-17 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_contact_email_alter_contact_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactstatus',
            options={'verbose_name': 'Contact Status'},
        ),
    ]
