# Generated by Django 6.0.1 on 2026-01-17 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_contactstatus_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactstatus',
            options={},
        ),
    ]
