# Generated by Django 6.0.1 on 2026-01-19 18:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_alter_contact_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Phone format: +99999999. Up to 15 digits.', regex='^\\+?[\\d\\s().-]{5,25}$')]),
        ),
    ]
